version: 0.0
os: linux
files:
  - source: /src
    destination: /var/www
  - source: /codedeploy/nginx/default.conf
    destination: /etc/nginx/conf.d
  - source: /codedeploy/nginx/php-fpm.conf
    destination: /etc/nginx/conf.d

hooks:
  ApplicationStart:
    - location: codedeploy/scripts/start_nginx.sh
      timeout: 300
      runas: root
  # AfterInstall:
  #   - location: codedeploy/scripts/after_install.sh
  #     timeout: 300
  #     runas: root
  ApplicationStop:
    - location: codedeploy/scripts/deregister_from_elb.sh
    - location: codedeploy/scripts/stop_nginx.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: codedeploy/scripts/verify.sh
    - location: codedeploy/scripts/register_with_elb.sh
